# Generated by Django 5.2.5 on 2025-09-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
